trigger: none

variables:
  - group: AWS_CREDENTIALS

stages:
  - stage: Build
    displayName: Build React + Next.js App
    jobs:
      - job: Build
        displayName: Build Job
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - script: |
              npm install --legacy-peer-deps
              npm run build
              echo "Current Dir: $(pwd)"
              ls -la
              ls -la .next/out
            displayName: 'Install Dependencies, Build, and List Exported Files'

          - task: CopyFiles@2
            inputs:
              SourceFolder: '.next/out'    # Changed from 'out' to '.next/export'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
            displayName: 'Copy Build Output'

          - publish: '$(Build.ArtifactStagingDirectory)'
            artifact: 'drop'
            displayName: 'Publish Artifact'

  - stage: Deploy
    displayName: Deploy to AWS S3
    dependsOn: Build
    jobs:
      - job: Deploy
        displayName: Deploy Job
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - download: current
            artifact: drop

          - script: |
              aws s3 sync $(Pipeline.Workspace)/drop s3://nextgenaitutors.com.au --delete
            env:
              AWS_ACCESS_KEY_ID: $(awsAccessKeyId)
              AWS_SECRET_ACCESS_KEY: $(awsSecretAccessKey)
              AWS_DEFAULT_REGION: 'ap-southeast-2'
            displayName: 'Sync files to S3 bucket'
