trigger: none

variables:
  - group: AWS_CREDENTIALS

stages:
  - stage: Build
    displayName: Build React + Next.js App
    jobs:
      - job: Build
        displayName: Build Job
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'  # Use the Node version compatible with your project
            displayName: 'Install Node.js'

          - script: |
              npm install --legacy-peer-deps
              npm run build
              npm run export
            displayName: 'Install Dependencies, Build, and Export'

          - task: CopyFiles@2
            inputs:
              SourceFolder: 'out'  # Ensure you're using `next export` for static build
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
            displayName: 'Copy Build Output'

          - publish: '$(Build.ArtifactStagingDirectory)'
            artifact: 'drop'
            displayName: 'Publish Artifact'

  - stage: Deploy
    displayName: Deploy to AWS S3
    dependsOn: Build
    jobs:
      - job: Deploy
        displayName: Deploy Job
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - download: current
            artifact: drop

          - task: AWSCLI@1
            displayName: 'Sync to S3 Bucket'
            inputs:
              awsCredentials: 'AWS_CREDENTIALS'
              regionName: 'ap-southeast-2'
              command: 's3'
              arguments: 'sync $(Pipeline.Workspace)/drop s3://nextgenaitutors.com.au --delete'
